import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import HeaderFixo from "../components/HeaderFixo";
import About from "../components/sections/About";
import Experience from "../components/sections/Experience";
import Jobs from "../components/sections/Jobs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Marlon.b | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderFixo />
      <Header />
      <About />
      <Experience />
      <Jobs />
      <Footer />
    </>
  )
}
